version: "3"

include:
  - path:
    - nl-shvirtd-example-python/proxy.yaml

volumes:
  db:

services:
  web:
    build:
      context: .
      dockerfile: ./Dockerfile.python
    image: cr.yandex/crpe719t8lr4rpibo4r6/pyapp:latest
    env_file:
      - .env
    environment:
      - DB_NAME=${DB_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_HOST=db
      - DB_TABLE=${DB_TABLE}
      - TZ='Europe/Moscow'
    restart: always
    depends_on:
      - db
    networks:
      backend:
        ipv4_address: 172.20.0.5

  db:
    image: mysql:8
    env_file:
      - .env
    command: --max_allowed_packet=256M
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - TZ='Europe/Moscow'
    volumes:
      - db:/var/lib/mysql
    restart: always
    networks:
      backend:
        ipv4_address: 172.20.0.10
